version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode
    networks:
      - devnet
  networks:
    devnet:
      driver: bridge
